export const GET_DATA_REQUEST= "GET_DATA_REQUEST";
export const GET_DATA_SUCCESS= "GET_DATA_SUCCESS";
export const GET_DATA_ERROR= "GET_DATA_ERROR";

export const GET_ENTERTAINMENT_REQUEST= "GET_ENTERTAINMENT_REQUEST";
export const GET_ENTERTAINMENT_SUCCESS= "GET_ENTERTAINMENT_SUCCESS";
export const GET_ENTERTAINMENT_ERROR= "GET_ENTERTAINMENT_ERROR";

export const GET_TECH_REQUEST= "GET_TECH_REQUEST";
export const GET_TECH_SUCCESS= "GET_TECH_SUCCESS";
export const GET_TECH_ERROR= "GET_TECH_ERROR";

export const GET_WORLD_REQUEST= "GET_WORLD_REQUEST";
export const GET_WORLD_SUCCESS= "GET_WORLD_SUCCESS";
export const GET_WORLD_ERROR= "GET_WORLD_ERROR";

export const GET_BUSINESS_REQUEST= "GET_BUSINESS_REQUEST";
export const GET_BUSINESS_SUCCESS= "GET_BUSINESS_SUCCESS";
export const GET_BUSINESS_ERROR= "GET_BUSINESS_ERROR";

export const GET_SCIENCE_REQUEST= "GET_SCIENCE_REQUEST";
export const GET_SCIENCE_SUCCESS= "GET_SCIENCE_SUCCESS";
export const GET_SCIENCE_ERROR= "GET_SCIENCE_ERROR";

export const GET_SPORTS_REQUEST= "GET_SPORTS_REQUEST";
export const GET_SPORTS_SUCCESS= "GET_SPORTS_SUCCESS";
export const GET_SPORTS_ERROR= "GET_SPORTS_ERROR";

export const GET_ARTICLE_REQUEST= "GET_ARTICLE_REQUEST";
export const GET_ARTICLE_SUCCESS= "GET_ARTICLE_SUCCESS";
export const GET_ARTICLE_ERROR= "GET_ARTICLE_ERROR";